services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_data:/opt/sonarqube/logs
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      VM_OPTIONS: "-Xmx512m -Xms512m"
      SONAR_ES_PATH_DATA: /opt/sonarqube/data/es8
      SONAR_ES_BOOTSTRAP_MEMORY_LOCK: false
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube

volumes:
  sonarqube_data: