pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'yumie913/nt548-lab02-exer03'
        DOCKER_HUB_CREDENTIALS = '2'
        SONARQUBE_SERVER = 'sonarqube-server'
        DOCKER_COMPOSE_PROD_FILE = 'docker-compose.prod.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/YumieNC/react-nginx-jenkins.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv(SONARQUBE_SERVER) {
                    sh 'sonarqube-scanner'
                }
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        def customImage = docker.build(DOCKER_IMAGE_NAME)
                        customImage.push()
                        customImage.push('latest')
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh "sudo docker-compose -f ${DOCKER_COMPOSE_PROD_FILE} up -d"
            }
        }
    }
    post {
        always {
            qualityGate abortPipeline: true, failOnTimeout: true, pollingTimeoutSecs: 120, serverUrl: 'http://sonarqube:9000/'
        }
    }
}
